name: Static Code Analysis
run-name: ${{github.actor}} is running static code analysis for SRF autosetup
on: [push]
jobs:
  flake8:
    runs-on: self-hosted
    steps:
      - run: echo "Starting static code analysis using flake8"
      - run: ls
      - run: python3 -m flake8 setup_gui.py
      - run: echo "Finished static code analysis using flake8"
